---
output:
  html_document:
    self_contained: true
---

```{r setup, echo = FALSE, warning = FALSE, error = FALSE, message = FALSE}

################################################################################
# 0. Controle de Pacotes e Fontes
## Carrega bibliotecas
library(dplyr)
library(gifski)
library(ggplot2)
library(gganimate)
library(ggpath)
library(ggtext)
library(glue)
library(magick)
library(purrr)
library(ragg)
library(stringr)
library(tidyr)

## Define parâmetros dos chunks
knitr::opts_chunk$set(echo = FALSE, warning = FALSE,
                      error = FALSE, message = FALSE)

################################################################################
# 1. Carregamento dos dados
## Carrega os dados obtidos a cada 5min
dados <- readRDS("dados.RDS")

## Cria uma tibble que associa informações dos candidatos
cand_info <- dplyr::tibble(
  candidato = c("LULA", "JAIR BOLSONARO"),
  partido = c("PT", "PL"),
  cor = c("#FF0A01", "#002B8F"),
  path = glue::glue("{partido}.png")
)

```

```{css}

#titulo {
  font-weight: bold;
  font-size: 50px;
  line-height: 55px;
  margin: 20px 0;
}

#subtitulo {
  font-size: 20px;
}

```

<!-- Insere título e subtítulo -->
<div id='titulo'>Apuração do 2º turno da disputa presidencial</div>
<div id='subtitulo'>⌚ Atualizações a cada 5min</div>

```{r}

################################################################################
# 2. Manejo dos dados
## Mantém apenas as variáveis de interesse e as renomeia
dados <- dados %>% 
  dplyr::select(candidato = nm,
                votos = vap,
                pct = pvap,
                data)

## Converte os valores de votos válidos e pct de caractere a númerico
dados <- dados %>% 
  dplyr::mutate(pct = stringr::str_replace(pct, ",", ".")) %>% 
  dplyr::mutate(across(.cols = c(pct, votos), .fns = as.numeric))

#################### TESTE ############################################
dados <- dados %>% 
mutate(pct = pct+sample.int(n()+1, n())/10)
#################### TESTE ############################################

## Adiciona informações dos candidatos
dados <- dados %>% dplyr::right_join(cand_info)

## Gera o texto
dados <- dados %>% 
  dplyr::mutate(label = glue("<strong style='font-size:7px;'>{candidato}</strong>
                             <span style='font-size:5px;'> ({partido})</span><br>
                             <span style='font-size:5px;'>{format(votos, big.mark='.', decimal.mark=',')}</span>"))

## Separa os dados dos candidatos
dados <- dados %>% 
  dplyr::group_by(partido) %>% 
  tidyr::nest()

################################################################################
# 3. Produção do gráfico
## Inicializa o objeto que guarda o gráfico
plot <- NULL %>% ggplot()

## Adiciona a série de cada candidato em uma camada diferente de ggplot
dados$data %>% purrr::walk(
  function(dados){
    
    p = plot +
      geom_path(aes(x = data, y = pct, color = I(cor)),
                size = 1, data = dados) +
      geom_point(aes(x = data, y = pct, color = I(cor)),
                 size = 7, data = dados) +
      ggtext::geom_richtext(aes(x = data, y = pct, label = label),
                            fill = "white", label.colour = NA,
                            label.margin = unit(c(0, 0, 0, 0.03), "npc"),
                            hjust = 0, size = 1.5, data = dados) +
      ggpath::geom_from_path(aes(x = data, y = pct, path = path),
                             width = 0.17, height = 0.17, data = dados)
    
    assign("plot", p, envir = .GlobalEnv)
    
  }
)

## Define limites do eixo-y, elementos do tema e da transição da animação
plot <- plot +
  scale_y_continuous(expand = expansion(mult = c(0.25,0.25)),
                     labels = scales::label_percent(scale = 1)) +
  scale_x_datetime(expand = expansion(mult = c(0.05,0.35))) +
  theme_minimal() +
  theme(
    text = element_text(size = 8),
    legend.position = 'none',
    axis.title = element_blank(),
    panel.grid.minor = element_blank(),
    plot.margin = margin(0.03,0.03,0.03,0.03,"npc")
  ) +
  gganimate::transition_reveal(along = data) +
  gganimate::ease_aes('quadratic-in-out')

## Define configurações da animação
gganimate::animate(plot, nframes = 350, fps = 60,
                   start_pause = 100, end_pause = 100,
                   device = 'ragg_png', res = 300,
                   width = 1500, height = 500)

```
