name: Scrap and Render
on:
  repository_dispatch:
    types: [run]
  schedule:
    - cron: '0/3 * * * *'
jobs:
  scrap-and-render:
    runs-on: macOS-latest
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession
    env:
      GITHUB_PAT: ${{ secrets.PAT_GITHUB }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      
      - name: Prepara o R
        uses: r-lib/actions/setup-r@v2      
      
      - name: Prepara o Pandoc (para o Markdown)
        uses: r-lib/actions/setup-pandoc@v2
        
      - name: Instala os pacotes do R
        run: |   
          install.packages(c("dplyr","gifski","ggplot2","gganimate","ggpath","ggtext","glue","jsonlite","lubridate","magick","purrr","rmarkdown","ragg","stringr","tidyr"))
        shell: Rscript {0}
     
      - name: Roda script de extração dos resultados (scrap) e produção da página (render)
        run: |   
          source("colher_de_pau.R")
        shell: Rscript {0}
      
      - name: Efetua commit dos resultados
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add --all
          git commit -m "Latest run: `date +'%Y-%m-%d %H:%M:%S'`" || exit 0
          git push
